Class {
	#name : #ClipRudesheim,
	#superclass : #Link,
	#category : #'Rudesheim-Example'
}

{ #category : #seam }
ClipRudesheim >> beginDrawWith:	aRHArgumentsForClip [
]

{ #category : #drawing }
ClipRudesheim >> drawWith:	aRHArgumentsForClip [
	
	^ self.
]

{ #category : #accessing }
ClipRudesheim >> duration [

	^ Duration new.
]

{ #category : #seam }
ClipRudesheim >> endDrawWith:	aRHArgumentsForClip [
]
